### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by Jefte** [ninthwalker/BattlegroundNotifier#2]
I'm trying to figure out what is triggering false positives in the OCR. Would it be possible to save any images that are recognized by the OCR to another directory for review later? That way I can review what caused it to flag positive.

**Comment by ninthwalker** [comment]
So I have only had a 'false positive' if I keep it running (Advanced option: stopOnQueue) while inside AV for example. At certain times when you cross areas it will say the zone you are in, which sometimes is 'Alterac Valley' See this screenshot I saved for reference of it fading in/out on the screen. [](https://imgur.com/a/bfcZRwQ) If the timing is right (20 second screenshot/OCR scans by default) then it will see that and flag that as if your BG popped.

If it is happening to you outside of that, im not sure. The OCR is pretty good ive found actually.
a couple things you can do:

1) Use the 'get coords' button to define your own little box for where your BG queue window pops and just 'draw' around the words it shows. By default i have it take the top middle third of the screen area, so most people would not need to use their own coordinates.

2) Other option is to change the words its looking to, to be more specific. On line 395, and then again for AV on line  402 is where you can see I'm just looking for 'Alterac'. you could change those 2 lines/words to be more specific for when the queue pops. It says 'you are now eligible to enter for alterac valley' so you could match on more words in that sentence if you wanted to.

3) If you still want to do your original question, and not overwrite the same screenshot, let me know and i can give you the lines of code to change for that.

Let me know if that helps. And thanks for the feedback.

**Comment by ninthwalker** [comment]
I will be updating the script to look for more precise words as the OCR of WIN10 seems to be pretty good. This should remove most false positives.
