### ISSUE TITLE
Close powershell.exe

### ISSUE THREAD

**Issue by GeoHolz** [ninthwalker/BattlegroundNotifier#4]
Hello,

When you have finished and click on the cross to exit, the window closes but the powershell.exe process continues to exist. This is a problem after a while

I just add "Stop-Process -Id $PID" at the end of file and it works
Is this the right way?

**Comment by ninthwalker** [comment]
Thanks for the report. You are right, in the BGNotifier shortcut, i left in the -noexit flag. I removed it in the latest change on github, You can also just right cliick and properties your shortcut and delete that flag as well.

You can also do what you did as well, although if I didn't mess up the shortcut, that wouldn't be needed as it'll close like its suppose to.
