### ISSUE TITLE
Alert on AFK  / Character Screen

### ISSUE THREAD

**Issue by wilsonhyng** [ninthwalker/BattlegroundNotifier#5]
I currently set it up to work with another AFK add on to alert me when I'm AFK for 23 minutes. This is different than the 'disconnect' alert. 

You usually get kicked out at 25-30 minutes. I think I might try expanding the OSR to detect something on the Character Screen but haven't had much luck yet.

**Comment by ninthwalker** [comment]
Closing, this won't be implemented on my end, sorry.
